export const typesAuth = {
  AUTH_USER_ADD_CREDENTIAL: 'authActions/AUTH_USER_ADD_CREDENTIAL',
  AUTH_USER_REVALIDATED_CREDENTIAL:
    'authActions/AUTH_USER_REVALIDATED_CREDENTIAL',
  AUTH_USER_ADD_ROL: 'authActions/AUTH_USER_ADD_ROL',
  AUTH_USER_CLEAR_CREDENTIAL: 'authActions/AUTH_USER_CLEAR_CREDENTIAL',
};
